<div class="page-head-alt button-level">
    <h3><?php echo Mage::helper('checkout')->__('Shopping Cart') ?></h3>
<!--    <?php if(!$this->hasError()): ?>
    <ul class="checkout-types">
        <?php echo $this->getChildHtml('top_methods') ?>
    </ul>
    <?php endif; ?>-->
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
<table cellspacing="0" border="0" id="shopping-cart-table" class="data-table box-table shopping-cart">
    <col width="40" />
    <col width="75" />
    <col />
<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
    <col width="1" />
<?php endif ?>
<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>
<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>
    <col width="1" />
<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>
<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>

<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
    <thead>
        <tr>
            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Remove') ?></th>
            <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
            <th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Product Name') ?></th>
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Move to Wishlist') ?></th>
            <?php endif ?>
            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Unit Price') ?></th>
            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
        </tr>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <tr>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
        </tr>
        <?php endif; ?>
    </thead>
    <tfoot>
        <tr>
            <td colspan="100" class="a-right">
                <?php if($this->getContinueShoppingUrl()): ?>
                    <button class="form-button-alt continue-shopping" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')" type="button"><span><?php echo $this->__('Continue Shopping') ?></span></button>
                <?php endif; ?>
                <button class="form-button-alt" type="submit"><span><?php echo $this->__('Update Shopping Cart') ?></span></button>
            </td>
        </tr>
    </tfoot>
    <tbody>
    <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('shopping-cart-table')</script>
</form>

<div class="shopping-cart-collaterals">
<div style="margin-left:15px;">
    <h4 style="color: #666; text-transform:uppercase;">Оформление заказа</h4>
    <form name="data-form" id="data-form" action="<?= $this->getCheckoutUrl() ?>" method="POST">
    <ul style="margin-top: 21px;">
        <li style="display:inline; margin-left: 21px;">
            <input name="checkout_method" id="local_ch" value="local" type="radio" onclick="changeLocation('<?= Riversy_Fastcheckout_Block_Oneclick_Form::TYPE_LOCAL ?>');"<?php if($this->getDefaultLocation() === Riversy_Fastcheckout_Block_Oneclick_Form::TYPE_LOCAL): ?> checked<?php endif; ?>>
            <label for="local_ch">Доставка по Москве и МО</label>
        </li>
        <li style="display:inline; margin-left: 21px;">
            <input name="checkout_method" id="other_ch" value="other" type="radio" onclick="changeLocation('<?= Riversy_Fastcheckout_Block_Oneclick_Form::TYPE_OTHER ?>');"<?php if($this->getDefaultLocation() === Riversy_Fastcheckout_Block_Oneclick_Form::TYPE_OTHER): ?> checked<?php endif; ?>>
            <label for="other_ch">Другой город</label>
        </li>
    </ul>    
    <div id="local_div" style="margin-top: 40px; margin-left:21px;display:<?php echo ($this->getDefaultLocation()==='local')?'block':'none'; ?>;"><?php echo $this->getFormHtml(Riversy_Fastcheckout_Block_Oneclick_Form::TYPE_LOCAL); ?></div>
    <div id="other_div" style="margin-top: 40px; margin-left:21px;display:<?php echo ($this->getDefaultLocation()==='other')?'block':'none'; ?>;"><?php echo $this->getFormHtml(Riversy_Fastcheckout_Block_Oneclick_Form::TYPE_OTHER); ?></div>

    </form>
</div>                 
    <?php if(!$this->hasError()): ?>
        <div style="text-align: left; margin-top:40px;">
        <ul class="checkout-types">
            <?php echo $this->getChildHtml('top_methods') ?>
        </ul>
        </div>
    <?php endif; ?>
</div>
<div class="right-container">
<div class="shopping-cart-totals">    
    <?php echo $this->getChildHtml('wp_totals'); ?>
    <?php if(!$this->hasError()): ?>
    <ul class="checkout-types">
        <?php  $this->getChildHtml('methods') ?>
    </ul>
    <?php endif; ?>
</div>
<div class="clear"></div>
<?php echo $this->getChildHtml('coupon') ?>
</div>
<div class="clear"></div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('data-form');
//]]>
</script>
    <script type="text/javascript">
    //<![CDATA[
    changeLocation('<?= $this->getDefaultLocation() ?>');
    function changeLocation(location){
        if ('<?= Riversy_Fastcheckout_Block_Oneclick_Form::TYPE_LOCAL ?>' == location){
            var l_disp = 'block';
            var o_disp = 'none';
        } else {
            var l_disp = 'none';
            var o_disp = 'block';
        }
        document.getElementById('local_div').style.display = l_disp;
        document.getElementById('other_div').style.display = o_disp;
        document.getElementById('local_totals').style.display = l_disp;
        document.getElementById('other_totals').style.display = o_disp;
    }
    //]]>
    </script>
