<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML dir=ltr lang=ru><HEAD><TITLE>Квитанция на оплату услуг для  riversy riversy</TITLE>
<META content="text/html; charset=utf-8" http-equiv=Content-Type>
<META content="MSHTML 5.00.3700.6699" name=GENERATOR></HEAD>
<BODY>
<CENTER>
<TABLE border=1 cellPadding=3 cellSpacing=0 width=600>
  <TBODY>
  <TR>
    <TD align=right height=255 vAlign=top width=240><BR><BR><FONT size=2>
      <P>Извещение</P></FONT><FONT
      size=1><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR>
      <P>Кассир</P><BR></FONT></FONT></TD>
    <TD align=right height=255 vAlign=center width=100>
           <TABLE border=1 cellPadding=3 cellSpacing=0 width=360><FONT size=-1>
        <P align=center>ИНН 7704646643, Сбербанк России ОАО Вернадское ОСБ №7970/1675 г. Москва<br>ООО "Добрый Дом"        <P></P></FONT><FONT size=1>получатель платежа</FONT>
        <TBODY>
        <TR>
          <TD align=middle colSpan=4 height=10 vAlign=center><FONT size=2>
            <P>Расчетный счет №: 40702810838180136186&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;БИК:
            044525225</P></FONT></TD></TR>
        <TR>
          <TD align=center colSpan=4 height=10 vAlign=middle><FONT size=2>
            <P>Кор. сч.: 30101810400000000225 &nbsp;&nbsp;&nbsp;&nbsp;КПП 770401001</P></FONT></TD></TR>
        <TR>
          <TD colSpan=4><FONT size=2>
            <CENTER><BR><?=$this->getReq() ?>&nbsp;<BR><BR></CENTER></FONT></TD></TR>
        <TR>
          <TD align=middle colSpan=2><FONT size=2>Вид платежа</FONT></TD>
          <TD align=middle><FONT size=2>Дата</FONT></TD>
          <TD align=middle><FONT size=2>Сумма</FONT></TD></TR>
        <TR>
          <TD align=middle colSpan=2><FONT size=1>Оплата услуг</FONT></TD>
          <TD align=middle><FONT size=2><?=$this->getDate()?></FONT><BR></TD>
          <TD align=middle><FONT size=2><?=$this->getPrice()?></FONT></TD></TR>
        <TR>
          <TD align=left colSpan=2 rowSpan=2><FONT
            size=2>Плательщик:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</FONT></TD>
          <TD align=middle><FONT size=1>Пеня:</FONT></TD>
          <TD align=middle>---<BR></TD></TR>
        <TR align=middle>
          <TD><FONT size=2>Всего:</FONT></TD>
          <TD><FONT size=2><?=$this->getPrice()?></FONT><BR></TD></TR></P></TABLE></TD></TR>
  <TR>
    <TD align=right height=255 vAlign=top width=240><FONT size=2><BR><BR>
      <P>Квитанция</P><BR><BR><BR><BR><BR><BR><BR><BR><BR><BR><FONT size=1>
      <P>Кассир</P><BR></FONT></FONT></TD>
    <TD align=right height=255 vAlign=center width=100>
      <TABLE border=1 cellPadding=3 cellSpacing=0 width=360><FONT size=-1>
        <P align=center>ИНН 7704646643, Сбербанк России ОАО Вернадское ОСБ №7970/1675 г. Москва<br>ООО "Добрый Дом"<P></P></FONT><FONT size=1>получатель платежа</FONT>
        <TBODY>
        <TR>
          <TD align=middle colSpan=4 height=10 vAlign=center><FONT size=2>
            <P>Расчетный счет №: 40702810838180136186&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;БИК:
            044525225</P></FONT></TD></TR>
        <TR>
          <TD align=center colSpan=4 height=10 vAlign=middle><FONT size=2>
            <P>Кор. сч.: 30101810400000000225 &nbsp;&nbsp;&nbsp;&nbsp;КПП 770401001</P></FONT></TD></TR>
        <TR>
          <TD colSpan=4><FONT size=2>
            <CENTER><BR><?=$this->getReq() ?>&nbsp;<BR><BR></CENTER></FONT></TD></TR>
        <TR>
          <TD align=middle colSpan=2><FONT size=2>Вид платежа</FONT></TD>
          <TD align=middle><FONT size=2>Дата</FONT></TD>
          <TD align=middle><FONT size=2>Сумма</FONT></TD></TR>
        <TR>
          <TD align=middle colSpan=2><FONT size=1>Оплата услуг</FONT></TD>
          <TD align=middle><FONT size=2><?=$this->getDate()?></FONT><BR></TD>
          <TD align=middle><FONT size=2><?=$this->getPrice()?></FONT></TD></TR>
        <TR>
          <TD align=left colSpan=2 rowSpan=2><FONT
            size=2>Плательщик:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</FONT></TD>
          <TD align=middle><FONT size=1>Пеня:</FONT></TD>
          <TD align=middle>---<BR></TD></TR>
        <TR align=middle>
          <TD><FONT size=2>Всего:</FONT></TD>
          <TD><FONT size=2><?=$this->getPrice()?></FONT><BR></TD></TR></P></TABLE></TD></TR></TBODY></TABLE></CENTER></BODY></HTML>

