    <p>Для оформления Вам достаточно заполнить имя, телефон и е-мейл и наш оператор перезвонит Вам в ближайшее время.</p>
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <ul class="form-list">
                <li>
                    <label for="billing:name" class="required">Имя <em>*</em></label>
                    <div class="input-box">

                        <input title="Имя"
                               name="local[name]"
                               id="billing:name"
                               value="<?php echo  $this->getName() ?>"
                               class="required-entry input-text"
                               type="text">
                    </div>

                </li>
                <li>
                    <label for="billing:phone" class="required">Телефон <em>*</em></label>
                    <div class="input-box">

                        <input title="Имя"
                               name="local[phone]"
                               id="billing:phone"
                               value="<?php echo  $this->getPhone() ?>"
                               class="required-entry input-text validate-phoneCheckout"
                               type="text">
                    </div>

                </li>

                <li>
                    <label for="billing:email" class="required">E-мейл <em>*</em></label>
                    <div class="input-box">

                        <input title="E-майл"
                               name="local[email]"
                               id="billing:email"
                               value="<?php echo  $this->getEmail() ?>"
                               class="input-text"
                               type="text">
                    </div>

                </li>
            </ul>
        </div>
        <div class="col-sm-12 col-md-6">
            <ul class="form-list">
                <li>
                    <label for="billing:street">Адрес доставки</label>
                    <div class="input-box">

                        <input title="Адрес доставки"
                               name="local[street]"
                               id="billing:street"
                               value="<?php echo  $this->getStreet() ?>"
                               class="input-text"
                               type="text">
                    </div>
                </li>

                <li>
                    <label for="billing:comment">Коментарий</label>
                    <div class="input-box">

                        <input title="Коментарий"
                               name="local[comment]"
                               id="billing:comment"
                               value="<?php echo  $this->getComment() ?>"
                               class="input-text"
                               type="text">
                    </div>
                </li>

                <?php if (Mage::helper('fastcheckout')->confExpressEnabled()): ?>
                <li>

                    <label for="billing:express" class="checkbox-inline express">
                        <input id="billing:express" type="checkbox" name="local[express]" value="ON" />

                        Экспресс доставка (+<?php echo  Mage::helper('fastcheckout')->confExpressPrice()?> руб)

                    </label>
                </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
    <input type="hidden" name="billing[locate]" value="<?php echo Riversy_Fastcheckout_Block_Form::TYPE_LOCAL?>" />
    <ul style="list-style-type:disc; margin: 20px 0 10px 0;">
        <li>Оплата производится наличными курьеру при получении заказа</li>
        <?php if ($this->showNotification()) { ?>
        <li>Поскольку сумма Вашего заказа менее <?php echo  $this->getMinSubtotal() ?> руб., минимальная стоимость доставки: <?php echo  $this->getShippingCost() ?> руб.</li>
      	<?php } else { ?>
      	<li>Поскольку сумма Вашего заказа более <?php echo  $this->getMinSubtotal() ?> руб., доставки в пределах МКАД - бесплатна.</li>
        <?php } ?>
        <li>Доставка за МКАД оплачивается дополнительно.</li>
    </ul>
