// Generated by CoffeeScript 1.9.3
(function() {
  var loading_mask, refreshHistory;

  loading_mask = "loading-mask";

  refreshHistory = function(params) {
    return new Ajax.Request(params.url.replace(/^http[s]{0,1}/, window.location.href.replace(/:[^:].*$/i, '')), {
      onSuccess: (function(_this) {
        return function(transport) {
          var content, error, response, success;
          try {
            response = eval('(' + transport.responseText + ')');
            success = response.success, content = response.content, error = response.error;
            if (success) {
              if ($(params.container_id)) {
                $(params.container_id).innerHTML = content;
              }
            }
          } catch (_error) {
            error = _error;
          }
          if (error) {
            return console.log(error);
          }
        };
      })(this)
    });
  };

}).call(this);

//# sourceMappingURL=history.js.map
