<div class="cart fast-checkout">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <div class="row no-margin">
        <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <fieldset>
                <table id="shopping-cart-table" class="table table-responsive no-border">
                    <col width="1" />
                    <col />
                    <col width="2" />
                    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <col width="1" />
                    <?php endif ?>
                    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col width="1" />
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col width="1" />
                    <?php endif; ?>
                    <col width="1" />
                    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col width="1" />
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col width="1" />
                    <?php endif; ?>
                    <col width="1" />

                    <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                    <thead>
                    <tr>
                        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product') ?></span></th>
                        <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>

                        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
                        <?php endif ?>
                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr">&nbsp;</span></th>
                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Price') ?></th>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Total') ?></th>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center">&nbsp;</th>
                    </tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <tr>
                            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        </tr>
                    <?php endif; ?>
                    </thead>
                    <tfoot>
                    <tr>
                        <td colspan="50" class="a-right">
                            <?php if($this->getContinueShoppingUrl()): ?>
                                <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                            <?php endif; ?>
                            <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                            <!--[if lt IE 8]>
                            <input type="hidden" id="update_cart_action_container" />
                            <script type="text/javascript">
                                //<![CDATA[
                                        Event.observe(window, 'load', function()
                                        {
                                            // Internet Explorer (lt 8) does not support value attribute in button elements
                                            $emptyCartButton = $('empty_cart_button');
                                            $cartActionContainer = $('update_cart_action_container');
                                            if ($emptyCartButton && $cartActionContainer) {
                                                Event.observe($emptyCartButton, 'click', function()
                                                {
                                                    $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                                    $cartActionContainer.setAttribute('name', 'update_cart_action');
                                                    $cartActionContainer.setValue('empty_cart');
                                                });
                                            }

                                        });
                                    //]]>
                                    </script>
                                    <![endif]-->
                        </td>
                    </tr>
                    </tfoot>
                    <tbody>
                    <?php foreach($this->getItems() as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach ?>
                    </tbody>
                </table>
            </fieldset>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </form>

        <div class="row no-margin">

            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">

                <h4 style="color: #666; text-transform:uppercase;">Оформление заказа</h4>
                <form name="data-form" id="data-form" action="<?php echo  $this->getCheckoutUrl() ?>" method="POST">
                    <div class="type-selector">

                        <label class="radio-inline">
                            <input name="checkout_method"
                                   class="optradio"
                                   id="local_ch"
                                   value="local"
                                   type="radio"
                                   onclick="changeLocation('<?php echo  Riversy_Fastcheckout_Block_Form::TYPE_LOCAL ?>');"<?php if($this->getDefaultLocation() === Riversy_Fastcheckout_Block_Form::TYPE_LOCAL): ?> checked<?php endif; ?>>

                            Доставка по Москве и МО
                        </label>
                        <label for="other_ch" class="radio-inline">
                            <input name="checkout_method"
                                   class="optradio"
                                   id="other_ch"
                                   value="other"
                                   type="radio"
                                   onclick="changeLocation('<?php echo  Riversy_Fastcheckout_Block_Form::TYPE_OTHER ?>');"<?php if($this->getDefaultLocation() === Riversy_Fastcheckout_Block_Form::TYPE_OTHER): ?> checked<?php endif; ?>>
                            Другой город
                        </label>
                    </div>

                    <div id="local_div" style="margin-top: 40px; margin-left:21px;display:<?php echo ($this->getDefaultLocation()==='local')?'block':'none'; ?>;"><?php echo $this->getFormHtml(Riversy_Fastcheckout_Block_Form::TYPE_LOCAL); ?></div>
                    <div id="other_div" style="margin-top: 40px; margin-left:21px;display:<?php echo ($this->getDefaultLocation()==='other')?'block':'none'; ?>;"><?php echo $this->getFormHtml(Riversy_Fastcheckout_Block_Form::TYPE_OTHER); ?></div>


                    <div class="checkout-button-set">
                        <?php echo  $this->getChildHtml('methods') ?>
                    </div>
                </form>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="col-totals">
                    <div class="totals">
                        <?php echo $this->getChildHtml('fastcheckout_totals'); ?>
                    </div>
                </div>

                <?php echo $this->getChildHtml('coupon') ?>
            </div>
        </div>
    </div>

    <div class="cart-collaterals">
        <?php echo $this->getChildHtml('crosssell') ?>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[

    var checkoutForm = new VarienForm('data-form');

    function changeLocation(location){
        if ('<?php echo Riversy_Fastcheckout_Block_Form::TYPE_LOCAL ?>' == location){
            var l_disp = 'block';
            var o_disp = 'none';
        } else {
            var l_disp = 'none';
            var o_disp = 'block';
        }
        document.getElementById('local_div').style.display = l_disp;
        document.getElementById('other_div').style.display = o_disp;
//        document.getElementById('local_totals').style.display = l_disp;
//        document.getElementById('other_totals').style.display = o_disp;
    }

    changeLocation('<?php echo $this->getDefaultLocation() ?>');
    //]]>
</script>
